### ISSUE TITLE
create a new html element

### ISSUE THREAD

**Issue by DrZYin** [HubSpot/youmightnotneedjquery#185] opened 2017-12-05 21:08 UTC
jQuery:
`foo = $("<div>")`
js:
`foo = Document.createElement("div");`

**Comment by Abbondanzo** [comment] 2021-09-12 07:47
Should be fixed by #226

**Comment by Abbondanzo** [comment] 2021-09-12 17:48
Duplicate of #48

**Closed as completed by Abbondanzo** 2021-09-12 17:48 UTC
Labels: duplicate, enhancement
