### ISSUE TITLE
Add IE 11 to the list of versions

### ISSUE THREAD

**Issue by Flimm** [HubSpot/youmightnotneedjquery#221] opened 2020-05-06 10:38 UTC
Internet Explorer 11 was released in 2013. I expect many developers do not need to support IE version older than 2013. For that reason, it would be useful to select that version. Right now, the newest version of IE that you can select is 10.

Compared to IE 10, IE 11 introduced partial support for EMCAScript 2015 (ES6) as well as other things ([see caniuse](https://caniuse.com/#compare=ie+10,ie+11)).

**Comment by mscuthbert** [comment] 2021-08-15 03:28
Or given that Microsoft is discontinuing IE on June 15, 2022, and turning off support for it in their own Office online suite this Tuesday, maybe have a full "ES6 (2015)" minimum tag.

**Comment by mscuthbert** [comment] 2021-10-11 15:06
Overlap / possible duplicate of #222

**Comment by jarikmarwede** [comment] 2022-07-20 07:45
If someone would make a PR that just added IE 11 to the versions toggle, would it be accepted? Or would you require at least one valid use case? @Abbondanzo

**Comment by Abbondanzo** [comment] 2022-07-20 12:08
> If someone would make a PR that just added IE 11 to the versions toggle, would it be accepted? Or would you require at least one valid use case? @Abbondanzo 

I'd be happy to accept just the toggle, but it won't be very useful without some cases.

**Closed as completed** 2022-08-26 18:55 UTC
Labels: enhancement

**Comment by Flimm** [comment] 2022-08-30 08:23
Fantastic! Thank you!

Since this issue was filed, Internet Explorer has been discontinued by Microsoft. See related issue: https://github.com/HubSpot/youmightnotneedjquery/issues/222
