### ISSUE TITLE
Offset section not working properly in Firefox

### ISSUE THREAD

**Issue by bfintal** [HubSpot/youmightnotneedjquery#122] opened 2015-06-03 09:44 UTC
Found out that FF was not working properly because `document.body.scrollTop` was returning 0 for that browser only.

Switching it to the more reliable `window.pageYOffset` works.

Same goes with `document.body.scrollLeft` to `window.pageXOffset`.

Original offset code:

```
var rect = el.getBoundingClientRect()

{
  top: rect.top + document.body.scrollTop,
  left: rect.left + document.body.scrollLeft
}
```

Revised offset code:

```
var rect = el.getBoundingClientRect()

{
  top: rect.top + window.pageYOffset,
  left: rect.left + window.pageXOffset
}
```

**Comment by dmitry** [comment] 2015-07-26 23:52
PS. window.pageYOffset is not supported below IE 9.

**Comment by bfintal** [comment] 2015-07-27 04:19
@dmitry We should note that in the offset section if it's changed to this: IE10+

**Comment by Krinkle** [comment] 2018-03-02 20:15
This is a duplicate of https://github.com/HubSpot/youmightnotneedjquery/issues/85.

**Comment by Abbondanzo** [comment] 2021-09-12 17:30
Closing in favor of #85

**Closed as completed by Abbondanzo** 2021-09-12 17:30 UTC
Labels: bug, duplicate
